### ISSUE TITLE
"Shipping" the compiled binaries to other windows machines?

### ISSUE THREAD

**Issue by beniroquai** [jacopoantonello/devwraps#2]
One more Question I had was, if it is possible to copy-paste the compiled binaries to other Windows (10) computers so that they do not need the Windows CPP compiler in order to get the code working. This would become very important. 

Thanks!

**Comment by jacopoantonello** [comment]
Hi! Once you have compiled the code it creates a `devwraps*.whl` file, I think in `dist/`. You can copy that to other computers and install it with `pip install devwraps*.whl`. Obviously you also need to install the corresponding drivers, e.g. ThorCam, as the wheel file only has the Python bindings.
